name: timer_app
description: Example app with provider

publish_to: 'none'

version: 0.0.1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  logger: ^1.3.0
  badges: ^3.1.0
  awesome_notifications: ^0.7.4+1
  connectivity_plus: ^3.0.4
  status_alert: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
